export const cities = [
  'New York',
  'Los Angeles',
  'Chicago',
  'Houston',
  'Phoenix',
  'Philadelphia',
  'San Antonio',
  'San Diego',
  'Dallas',
  'San Jose',
  'Austin',
  'Jacksonville',
  'Fort Worth',
  'Columbus',
  'San Francisco',
  'Charlotte',
  'Indianapolis',
  'Seattle',
  'Denver',
  'Washington',
  'Boston',
  'El Paso',
  'Nashville',
  'Detroit',
  'Oklahoma City',
  'Portland',
  'Las Vegas',
  'Memphis',
  'Louisville',
  'Baltimore',
  'Milwaukee',
  'Albuquerque',
  'Tucson',
  'Fresno',
  'Sacramento',
  'Kansas City',
  'Mesa',
  'Atlanta',
  'Omaha',
  'Colorado Springs',
  'Raleigh',
  'Miami',
  'Long Beach',
  'Virginia Beach',
  'Oakland',
  'Minneapolis',
  'Tulsa',
  'Arlington',
  'Tampa',
  'New Orleans',
  'Wichita',
  'Cleveland',
  'Bakersfield',
  'Aurora',
  'Anaheim',
  'Honolulu',
  'Santa Ana',
  'Riverside',
  'Corpus Christi',
  'Lexington',
  'Stockton',
  'Henderson',
  'Saint Paul',
  'St. Louis',
  'Saint Petersburg',
  'Pittsburgh',
  'Greensboro',
  'Lincoln',
  'Anchorage',
  'Plano',
  'Orlando',
  'Irvine',
  'Newark',
  'Durham',
  'Chula Vista',
  'Toledo',
  'Fort Wayne',
  'Jersey City',
  'Chandler',
  'Madison',
  'Laredo',
  'Buffalo',
  'Lubbock',
  'Scottsdale',
  'Reno',
  'Glendale',
  'Gilbert',
  'Winston-Salem',
  'North Las Vegas',
  'Norfolk',
  'Chesapeake',
  'Garland',
  'Irving',
  'Hialeah',
  'Fremont',
  'Boise',
  'Richmond',
  'Baton Rouge',
  'Spokane',
  'Des Moines',
  'Tacoma',
  'San Bernardino',
  'Modesto',
  'Fontana',
  'Santa Clarita',
  'Birmingham',
  'Oxnard',
  'Fayetteville',
  'Moreno Valley',
  'Rochester',
  'Glendale',
  'Huntington Beach',
  'Salt Lake City',
  'Grand Rapids',
  'Amarillo',
  'Yonkers',
  'Aurora',
  'Montgomery',
  'Akron',
  'Little Rock',
  'Huntsville',
  'Augusta',
  'Port St. Lucie',
  'Grand Prairie',
  'Columbus',
  'Tallahassee',
  'Overland Park',
  'Tempe',
  'McKinney',
  'Mobile',
  'Cape Coral',
  'Shreveport',
  'Frisco',
  'Knoxville',
  'Worcester',
  'Brownsville',
  'Vancouver',
  'Fort Lauderdale',
  'Sioux Falls',
  'Peoria',
  'Ontario',
  'Jackson',
  'Elk Grove',
  'Salem',
  'Springfield',
  'Corona',
  'Eugene',
  'Pembroke Pines',
  'Salinas',
  'Provo',
  'Lansing',
  'Springfield',
  'Pasadena',
  'Fort Collins',
  'Hayward',
  'Pomona',
  'Cary',
  'Rockford',
  'Alexandria',
  'Escondido',
  'Kansas City',
  'Joliet',
  'Sunnyvale',
  'Torrance',
  'Bridgeport',
  'Lakewood',
  'Hollywood',
  'Paterson',
  'Naperville',
  'Syracuse',
  'Mesquite',
  'Dayton',
  'Savannah',
  'Clarksville',
  'Orange',
  'Pasadena',
  'Fullerton',
  'Killeen',
  'Hampton',
  'McAllen',
  'Warren',
  'Bellevue',
  'West Valley City',
  'Columbia',
  'Olathe',
  'Sterling Heights',
  'New Haven',
  'Miramar',
  'Waco',
  'Thousand Oaks',
  'Cedar Rapids',
  'Charleston',
  'Visalia',
  'Topeka',
  'Elizabeth',
  'Gainesville',
  'Thornton',
  'Roseville',
  'Carrollton',
  'Coral Springs',
  'Stamford',
  'Simi Valley',
  'Concord',
  'Hartford',
  'Kent',
  'Lafayette',
  'Midland',
  'Surprise',
  'Denton',
  'Victorville',
  'Evansville',
  'Santa Rosa',
  'Vallejo',
  'Athens',
]
